### ISSUE TITLE
Support renaming directories of directories

### ISSUE THREAD

**Issue by IvantheTricourne** [mtimkovich/slippi-tagger#11]
A lot of people (including myself) like to structure their `Slippi` directories by month. 

```
Slippi
├── 2020-08
├── 2020-09
├── 2020-10
```

Since this is an option for the rollback build, this script should support renaming files within sub-directories.

**Comment by mtimkovich** [comment]
Good idea! I'll implement it when I'm free

**Comment by mtimkovich** [comment]
ed298c9d5a0f60daf260be654b078f2a47e85915

Passing the `-r` flag when running the script will rename inside subdirectories as well.
