### ISSUE TITLE
Allow renamed files to be re-renamed

### ISSUE THREAD

**Issue by IvantheTricourne** [mtimkovich/slippi-tagger#8]
This basically allows any file that has already been renamed to be renamed again. This will allow users with renamed files to use newer versions/features of this script (i.e., the netplay names). It will also allow users that don't keep their `.slp` files named under the normal `Game_<DATE>.slp` pattern to use this script.

This is also relatively simple and can be accomplished several ways: 

1. Use another regex to match the date string prefix of a renamed file
2. Remove the reliance on regexes altogether and use slippi file `metadata` to construct the date prefix

IMO, option 2 is significantly better but poses the issue of older slippi files (i.e., slippi files without metadata) being unable to be prefixed with a date, which necessitates the use of the regex.

**Comment by IvantheTricourne** [comment]
For example, most `.slp` files have the following information available in their `metadata`:

```
{
  startAt: '2020-06-14T01:52:35Z',
  lastFrame: 11847,
  players: {
    '0': { names: [Object], characters: [Object] },
    '1': { names: [Object], characters: [Object] }
  },
  playedOn: 'dolphin'
}
```

This is the same data where netplay names are stored.

**Comment by mtimkovich** [comment]
I like option 2 also. It could grab the timestamp if there is one, otherwise just rename without it.
